version: 2
updates:
- package-ecosystem: npm
  directory: "/client"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - automerge
  ignore:
  - dependency-name: jsoneditor
    versions:
    - 9.1.10
    - 9.1.9
    - 9.2.0
    - 9.3.0
    - 9.3.1
    - 9.4.0
  - dependency-name: core-js
    versions:
    - 3.10.0
    - 3.10.1
    - 3.10.2
    - 3.8.3
    - 3.9.0
    - 3.9.1
  - dependency-name: vuetify
    versions:
    - 2.4.11
    - 2.4.3
    - 2.4.4
    - 2.4.5
    - 2.4.6
    - 2.4.7
    - 2.4.8
    - 2.4.9
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: "@vue/cli-plugin-eslint"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.11
- package-ecosystem: docker
  directory: "/client"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - automerge
- package-ecosystem: docker
  directory: "/comrade"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - automerge
  ignore:
  - dependency-name: python
    versions:
    - 3.9.1.pre.slim
    - 3.9.2.pre.slim
    - 3.9.3.pre.slim
- package-ecosystem: pip
  directory: "/comrade"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  labels:
  - automerge
  allow:
  - dependency-type: direct
  - dependency-type: indirect
